#!/usr/bin/env python3
"""Generate every agent's GLOBAL instruction file from shared fragments.

Single source of truth for machine-wide agent guidance (browser automation,
secrets, git policy, ...). Fragments live in global/fragments/; this script
assembles them into each agent's global instruction file. Run with no arguments
to (re)write all generated files; run with --check to verify none have drifted
(used by the lefthook pre-commit hook).

Why a generator instead of native @imports: only Claude Code and Gemini CLI
support in-file @path imports; Codex and OpenCode have none, and Antigravity's
`agy` (closed-source rewrite) is unverified. A generator is the only DRY
mechanism that works uniformly across every agent — same pattern as
permissions/sync.py. OpenCode gets no file of its own: it inherits the fully
expanded ~/.claude/CLAUDE.md as a global-rules fallback (read literally).

Generated files:
    claude/CLAUDE.md              -> ~/.claude/CLAUDE.md (default profile)
    claude/CLAUDE.autonomous.md   -> ~/.claude/CLAUDE.md (--autonomous profile)
    global/AGENTS.md              -> ~/.codex/AGENTS.md AND ~/.gemini/GEMINI.md
                                     AND ~/.pi/agent/AGENTS.md
                                     (one shared file for every non-Claude agent)
"""

from __future__ import annotations

import difflib
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRAGMENTS = REPO_ROOT / "global" / "fragments"

HEADER = (
    "<!-- GENERATED by global/sync.py — do not edit. "
    "Edit the fragments in global/fragments/ and re-run global/sync.py. -->"
)

INTRO = """# Global {title}

User-scoped guidance that applies to every {session} on this machine. Loaded from `{self_path}` (symlinked to this file).

Keep this file **project-agnostic** — anything specific to a particular repo belongs in that repo's own `{repo_file}`."""

# Generic intro for the shared non-Claude file (symlinked to more than one path,
# so it can't name a single self_path the way the per-agent template does).
SHARED_INTRO = """# Global agent instructions

User-scoped guidance that applies to every agent session on this machine. Installed to `~/.codex/AGENTS.md` (Codex), `~/.gemini/GEMINI.md` (Antigravity `agy`), and `~/.pi/agent/AGENTS.md` (Pi).

Keep this file **project-agnostic** — anything specific to a particular repo belongs in that repo's own `AGENTS.md`."""

# Each target assembles: intro + ordered fragments. Web-fetching (the Jina MCP) now
# has two variants: `web-fetching` names Claude's exact tool names (mcp__jina__*,
# WebFetch); `web-fetching.shared` is tool-agnostic for the other agents, which reach
# Jina via their own MCP integrations (Codex config.toml, Antigravity mcp_config.json,
# Pi's mcp-adapter). Everything else is agent-agnostic. Claude gets its own CLAUDE.md
# (it needs the CLAUDE.md filename and the autonomous git-policy swap). Every other
# agent shares ONE file — byte-identical content — symlinked to each agent's global
# path; we don't branch per-agent until one actually needs something different.
TARGETS = [
    {
        "path": "claude/CLAUDE.md",
        "title": "CLAUDE.md",
        "session": "Claude Code session",
        "self_path": "~/.claude/CLAUDE.md",
        "repo_file": "CLAUDE.md",
        "fragments": [
            "web-fetching", "browser-automation", "secrets",
            "git-policy", "git-commit-policy", "working-style",
        ],
    },
    {
        "path": "claude/CLAUDE.autonomous.md",
        "title": "CLAUDE.md",
        "session": "Claude Code session",
        "self_path": "~/.claude/CLAUDE.md",
        "repo_file": "CLAUDE.md",
        "fragments": [
            "web-fetching", "browser-automation", "secrets",
            "git-policy.autonomous", "git-commit-policy", "working-style",
        ],
    },
    {
        "path": "global/AGENTS.md",
        "intro": SHARED_INTRO,
        "fragments": [
            "web-fetching.shared", "browser-automation", "secrets",
            "git-policy", "git-commit-policy", "working-style",
        ],
    },
]


def load_fragment(name):
    path = FRAGMENTS / f"{name}.md"
    if not path.exists():
        sys.exit(f"fragment not found: {path.relative_to(REPO_ROOT)}")
    return path.read_text().strip()


def render(target):
    intro = target.get("intro") or INTRO.format(
        title=target["title"],
        session=target["session"],
        self_path=target["self_path"],
        repo_file=target["repo_file"],
    )
    blocks = [HEADER, intro]
    blocks += [load_fragment(name) for name in target["fragments"]]
    return "\n\n".join(blocks) + "\n"


def render_all():
    return {REPO_ROOT / t["path"]: render(t) for t in TARGETS}


def atomic_write(path, content):
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".sync-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def write_all():
    for path, content in render_all().items():
        path.parent.mkdir(parents=True, exist_ok=True)  # e.g. gemini output dir may be new
        atomic_write(path, content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def check_all():
    drift = []
    for path, expected in render_all().items():
        actual = path.read_text() if path.exists() else ""
        if actual != expected:
            drift.append((path, actual, expected))
    if not drift:
        print("global instruction files are up to date")
        return 0
    for path, actual, expected in drift:
        rel = path.relative_to(REPO_ROOT)
        print(f"DRIFT: {rel}", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)",
                tofile=f"{rel} (expected)",
            )
        )
    print(
        f"\n{len(drift)} global instruction file(s) out of sync — "
        "run global/sync.py to regenerate.",
        file=sys.stderr,
    )
    return 1


def main(argv):
    if not FRAGMENTS.is_dir():
        print(f"fragments not found: {FRAGMENTS}", file=sys.stderr)
        return 1
    if argv == ["--check"]:
        return check_all()
    if argv:
        print(f"usage: {Path(__file__).name} [--check]", file=sys.stderr)
        return 2
    write_all()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
