#!/usr/bin/env python3
"""Generate harness-specific SKILL.md files from shared templates.

Single source of truth for multi-harness skills (e.g. second-opinion).
Templates live in skills/; this script generates:
    claude/skills/second-opinion/SKILL.md -> for Claude host
    codex/skills/second-opinion/SKILL.md  -> for Codex/AGY/Pi host

Run with no arguments to (re)write all generated files; run with --check to
verify none have drifted (used by lefthook pre-commit hook).
"""

from __future__ import annotations

import difflib
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
TEMPLATE_FILE = SKILLS_DIR / "second-opinion.template.md"

HEADER = (
    "<!-- GENERATED by skills/sync.py — do not edit. "
    "Edit skills/second-opinion.template.md and re-run skills/sync.py. -->"
)

TARGETS = [
    {
        "path": "claude/skills/second-opinion/SKILL.md",
        "replacements": {
            "DESCRIPTION": "Get external AI opinions on a problem or question. Use when you want diverse perspectives from Codex and OpenCode+GLM.",
            "INTRO": "Get input from two independent advisors — Codex (GPT) and OpenCode+GLM — on the current problem or question. By default, iterates if responses lack confidence.",
            "CLI_DEPS_GOTCHA": "Both CLIs (`codex`, `opencode`) must be installed. If one is missing or fails, the command continues with the other and that advisor's input is simply absent from the synthesis.",
            "ADVISOR_GOTCHAS": (
                "- **Codex** blocks on \"Reading additional input from stdin...\" unless stdin is closed (`</dev/null`), and prompts for confirmation outside a git repo unless given `--skip-git-repo-check`.\n"
                "- **Antigravity (`agy`) was dropped from this skill** (2026-07). In headless/print mode the current `agy` soft-denies *every* file read and command — the `permissions.allow` list, workspace registration, and trusted-folder status are only honored interactively, not headlessly (verified: even a `read_file` on a file inside a trusted+registered workspace is soft-denied). The only way to make it produce output is `--dangerously-skip-permissions` (or `toolPermission: always-proceed`), which auto-approves **all** tools including writes — there is no read-only-with-exploration path. Rather than grant blanket write access for a read-only consult, `agy` is left out. Do **not** re-add it without re-verifying headless behavior against a newer build.\n"
                "- **OpenCode** bills through OpenRouter — models must use the `openrouter/` prefix (`opencode/*` is OpenCode Zen, which has no payment method and errors out). Use `--agent plan`, **not** the default `build` agent: `plan` can read/explore the repo but has no write tools, so it gives a code-aware opinion without editing anything.\n"
                "- **Headless gotcha:** OpenCode evaluates each part of a compound (`;`/`&&`/`|`) bash command separately and takes the least-permitted verdict; with stdin closed there's no TTY to answer an `ask` prompt, so the whole call is auto-rejected and the run terminates before producing any prose. The classic trigger is a benign `echo ---` separator inside an otherwise-allowed read chain. The prompt template already tells the advisor to avoid chaining; if a run still dies with no output, suspect a chained command hitting an un-allowlisted token (allowlist source: `~/ac/permissions/permissions.toml`)."
            ),
            "COMMAND_PREFIX_NOTE": (
                "Prefix `codex` and `opencode` with the `command` builtin: in some shells they are\n"
                "`sops exec-env` wrapper functions that depend on an interactive-shell variable not\n"
                "present in the agent's environment; `command` bypasses the wrapper and runs the real\n"
                "binary, which authenticates via its own on-disk credentials."
            ),
            "QUERY_COMMANDS": (
                "**Codex (GPT):** `--skip-git-repo-check` so it works outside a git repo:\n"
                "```bash\n"
                'command codex exec -s read-only --skip-git-repo-check "$(cat .second-opinion.md)" </dev/null\n'
                "```\n\n"
                "**OpenCode+GLM:** `--agent plan` is read-only (reads/explores the repo, cannot edit files):\n"
                "```bash\n"
                'command opencode run --agent plan -m openrouter/z-ai/glm-5.2 "$(cat .second-opinion.md)" </dev/null\n'
                "```"
            ),
            "PRESENT_RESULTS_TEMPLATE": (
                "### Codex (GPT)\n"
                "{codex_response}\n\n"
                "### OpenCode (GLM)\n"
                "{glm_response}"
            ),
        },
    },
    {
        "path": "codex/skills/second-opinion/SKILL.md",
        "replacements": {
            "DESCRIPTION": "Get external AI opinions on a problem or question. Use when you want diverse perspectives from Claude and OpenCode+GLM.",
            "INTRO": "Get input from two independent advisors — Claude (Anthropic) and OpenCode+GLM — on the current problem or question. By default, iterates if responses lack confidence.",
            "CLI_DEPS_GOTCHA": "Both CLIs (`claude`, `opencode`) must be installed. If one is missing or fails, the command continues with the other and that advisor's input is simply absent from the synthesis.",
            "ADVISOR_GOTCHAS": (
                "- **Claude** runs non-interactively in print mode (`claude -p`). Give it the read-only built-ins (`--tools \"Read,Grep,Glob\"`) so it can explore but not edit, and `--disable-slash-commands` so it can't recurse into skills. Do **not** prefix it with `command`: Claude Code authenticates from a credential injected into the session's environment by the `sops exec-env` wrapper, so the bare name (which inherits that env, or re-enters the wrapper in a login shell) is what works. A bare binary with no injected credential exits immediately with `Not logged in · Please run /login`.\n"
                "- **OpenCode** bills through OpenRouter — models must use the `openrouter/` prefix (`opencode/*` is OpenCode Zen, which has no payment method and errors out). Use `--agent plan`, **not** the default `build` agent: `plan` can read/explore the repo but has no write tools, so it gives a code-aware opinion without editing anything.\n"
                "- **Headless gotcha:** OpenCode evaluates each part of a compound (`;`/`&&`/`|`) bash command separately and takes the least-permitted verdict; with stdin closed there's no TTY to answer an `ask` prompt, so the whole call is auto-rejected and the run terminates before producing any prose. The classic trigger is a benign `echo ---` separator inside an otherwise-allowed read chain. The prompt template already tells the advisor to avoid chaining; if a run still dies with no output, suspect a chained command hitting an un-allowlisted token (allowlist source: `~/ac/permissions/permissions.toml`)."
            ),
            "COMMAND_PREFIX_NOTE": (
                "Prefix `opencode` with the `command` builtin: in some shells it is a `sops exec-env`\n"
                "wrapper function that depends on an interactive-shell variable not present in the\n"
                "agent's environment; `command` bypasses the wrapper and runs the real binary, which\n"
                "authenticates via its own on-disk credentials. Leave `claude` unprefixed — it needs\n"
                "the injected credential the wrapper (or the inherited session env) provides."
            ),
            "QUERY_COMMANDS": (
                "**Claude (Anthropic):** read-only built-ins, no slash commands, print mode:\n"
                "```bash\n"
                'claude --tools "Read,Grep,Glob" --disable-slash-commands --no-session-persistence -p "$(cat .second-opinion.md)" </dev/null\n'
                "```\n\n"
                "**OpenCode+GLM:** `--agent plan` is read-only (reads/explores the repo, cannot edit files):\n"
                "```bash\n"
                'command opencode run --agent plan -m openrouter/z-ai/glm-5.2 "$(cat .second-opinion.md)" </dev/null\n'
                "```"
            ),
            "PRESENT_RESULTS_TEMPLATE": (
                "### Claude (Anthropic)\n"
                "{claude_response}\n\n"
                "### OpenCode (GLM)\n"
                "{glm_response}"
            ),
        },
    },
]


def render(target: dict) -> str:
    content = TEMPLATE_FILE.read_text()
    for key, value in target["replacements"].items():
        placeholder = f"{{{{{key}}}}}"
        if placeholder not in content:
            sys.exit(f"placeholder {placeholder} not found in {TEMPLATE_FILE.name}")
        content = content.replace(placeholder, value)
    return insert_header(content)


# The banner must sit *below* the YAML frontmatter: every harness requires the
# opening `---` on line 1, and anything above it makes the frontmatter unparsed
# (the skill then shows the banner as its description).
def insert_header(content: str) -> str:
    if not content.startswith("---\n"):
        sys.exit(f"{TEMPLATE_FILE.name} must start with YAML frontmatter")
    end = content.index("\n---\n", 4) + len("\n---\n")
    return content[:end] + "\n" + HEADER + "\n" + content[end:]


def render_all() -> dict[Path, str]:
    return {REPO_ROOT / t["path"]: render(t) for t in TARGETS}


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".sync-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def write_all() -> None:
    for path, content in render_all().items():
        atomic_write(path, content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def check_all() -> int:
    drift = []
    for path, expected in render_all().items():
        actual = path.read_text() if path.exists() else ""
        if actual != expected:
            drift.append((path, actual, expected))
    if not drift:
        print("skill files are up to date")
        return 0
    for path, actual, expected in drift:
        rel = path.relative_to(REPO_ROOT)
        print(f"DRIFT: {rel}", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)",
                tofile=f"{rel} (expected)",
            )
        )
    print(
        f"\n{len(drift)} skill file(s) out of sync — "
        "run skills/sync.py to regenerate.",
        file=sys.stderr,
    )
    return 1


def main(argv: list[str]) -> int:
    if not TEMPLATE_FILE.is_file():
        print(f"template not found: {TEMPLATE_FILE}", file=sys.stderr)
        return 1
    if argv == ["--check"]:
        return check_all()
    if argv:
        print(f"usage: {Path(__file__).name} [--check]", file=sys.stderr)
        return 2
    write_all()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
