#!/usr/bin/env python3
"""Generate every agent's MCP server config from mcp/servers.toml.

mcp/servers.toml is the single source of truth. Run this script with no
arguments to (re)write all generated files; run it with --check to verify they
are up to date (exit 1 with a diff on drift).

Generated files:
  claude/mcp-servers.generated.json   (input to `claude mcp add-json`)
  codex/config.toml                   ([mcp_servers.*] tables)
  ~/.config/opencode/opencode.json    (the `mcp` key only)
  pi/mcp.json                         (static import — see render_pi)

This owns server DEFINITIONS (url / command / auth env var). Which of their
tools may be called is permissions/permissions.toml's `[mcp]` section, rendered
by loadout. The two write disjoint keys of ~/.config/opencode/opencode.json —
`mcp` here, `permission` there. loadout declares `preserve = ["mcp"]` and passes
this key through untouched, so this generator must keep reading the current file
and mutating only its own key.

Claude Code is the odd one out: ~/.claude.json is runtime state (session
history, project entries, caches) and cannot be symlinked, and
~/.claude/settings.json has no mcpServers key. So claude/mcp-servers.generated
.json is generated but NOT symlinked — sync.sh feeds it to `claude mcp
add-json --scope user` for any server not already registered.
"""

from __future__ import annotations

import difflib
import json
import os
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "mcp" / "servers.toml"

HEADER_LINES = [
    "GENERATED by mcp/sync.py — do not edit.",
    "Edit mcp/servers.toml and re-run mcp/sync.py.",
]


# --------------------------------------------------------------------------
# source
# --------------------------------------------------------------------------

def parse_source():
    with SOURCE.open("rb") as f:
        data = tomllib.load(f)
    servers = {}
    for name in sorted(data):
        spec = data[name]
        transport = spec.get("transport")
        if transport == "http":
            if not spec.get("url"):
                raise ValueError(f"{name}: http transport requires a url")
        elif transport == "stdio":
            if not spec.get("command"):
                raise ValueError(f"{name}: stdio transport requires a command")
        else:
            raise ValueError(f"{name}: transport must be 'http' or 'stdio'")
        servers[name] = spec
    return servers


def is_http(spec):
    return spec["transport"] == "http"


def argv(spec):
    return list(spec.get("args", []))


def env(spec):
    return dict(spec.get("env", {}))


# --------------------------------------------------------------------------
# claude — claude/mcp-servers.generated.json: the exact per-server shape
# `claude mcp add-json` takes, which is also how it stores them in
# ~/.claude.json. Header interpolation is ${VAR}.
# --------------------------------------------------------------------------

def render_claude(servers):
    path = REPO_ROOT / "claude" / "mcp-servers.generated.json"
    config = {}
    for name, spec in servers.items():
        if is_http(spec):
            entry = {"type": "http", "url": spec["url"]}
            auth = spec.get("auth_env_var")
            if auth:
                entry["headers"] = {"Authorization": f"Bearer ${{{auth}}}"}
        else:
            entry = {
                "type": "stdio",
                "command": spec["command"],
                "args": argv(spec),
                "env": env(spec),
            }
        config[name] = entry
    return {path: json.dumps(config, indent=2, ensure_ascii=False) + "\n"}


# --------------------------------------------------------------------------
# codex — codex/config.toml: full regen. codex/sync_config.py merges this into
# ~/.codex/config.toml (and re-serializes through tomllib, so the header
# comment is dropped there — it only guards the repo copy).
# --------------------------------------------------------------------------

def toml_string(value):
    return json.dumps(value)


def toml_array(values):
    return "[" + ", ".join(toml_string(v) for v in values) + "]"


def render_codex(servers):
    path = REPO_ROOT / "codex" / "config.toml"
    lines = [f"# {line}" for line in HEADER_LINES]
    for name, spec in servers.items():
        lines.append("")
        lines.append(f"[mcp_servers.{name}]")
        if is_http(spec):
            lines.append(f"url = {toml_string(spec['url'])}")
            auth = spec.get("auth_env_var")
            if auth:
                lines.append(f"bearer_token_env_var = {toml_string(auth)}")
        else:
            lines.append(f"command = {toml_string(spec['command'])}")
            args = argv(spec)
            if args:
                lines.append(f"args = {toml_array(args)}")
            variables = env(spec)
            if variables:
                lines.append("")
                lines.append(f"[mcp_servers.{name}.env]")
                for key in sorted(variables):
                    lines.append(f"{key} = {toml_string(variables[key])}")
    return {path: "\n".join(lines) + "\n"}


# --------------------------------------------------------------------------
# opencode — opencode.json: replace the `mcp` key, preserve everything else
# (notably `permission`, which loadout owns). A local server takes
# one `command` array combining command and args, not separate fields, and
# interpolation is {env:VAR} rather than ${VAR}.
#
# This one writes the real destination rather than a staged copy, because
# loadout writes it there too and both generators have to see one file. Run
# this before loadout so its `preserve = ["mcp"]` has the current key to keep.
# --------------------------------------------------------------------------

OPENCODE_CONFIG = Path(
    os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")
) / "opencode" / "opencode.json"


def render_opencode(servers):
    path = OPENCODE_CONFIG
    config = json.loads(path.read_text()) if path.exists() else {}
    mcp = {}
    for name, spec in servers.items():
        if is_http(spec):
            entry = {"type": "remote", "url": spec["url"]}
            auth = spec.get("auth_env_var")
            if auth:
                entry["headers"] = {"Authorization": f"Bearer {{env:{auth}}}"}
        else:
            entry = {"type": "local", "command": [spec["command"]] + argv(spec)}
            variables = env(spec)
            if variables:
                entry["environment"] = variables
        mcp[name] = entry
    config["mcp"] = mcp
    return {path: json.dumps(config, indent=2, ensure_ascii=False) + "\n"}


# --------------------------------------------------------------------------
# pi — pi/mcp.json: a static import, not a rendering of `servers`. Pi's
# pi-mcp-adapter resolves the "claude-code" import kind by reading
# ~/.claude.json directly, so Pi already sees whatever sync.sh registered with
# Claude. Kept under this generator's --check gate so the file can't drift
# into a hand-maintained second copy of the server list.
# --------------------------------------------------------------------------

def render_pi(servers):
    path = REPO_ROOT / "pi" / "mcp.json"
    return {path: json.dumps({"imports": ["claude-code"]}, indent=2) + "\n"}


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def render_all():
    servers = parse_source()
    files = {}
    files.update(render_claude(servers))
    files.update(render_codex(servers))
    files.update(render_opencode(servers))
    files.update(render_pi(servers))
    return files


def display(path):
    """Not every output lives in the repo any more."""
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def atomic_write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".sync-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def write_all():
    files = render_all()
    originals = {
        path: path.read_text() if path.exists() else None
        for path in files
    }
    try:
        for path, content in files.items():
            atomic_write(path, content)
            print(f"wrote {display(path)}")
    except BaseException:
        for path, content in originals.items():
            if content is None:
                if path.exists():
                    path.unlink()
            else:
                atomic_write(path, content)
        raise


def check_all():
    drift = []
    for path, expected in render_all().items():
        actual = path.read_text() if path.exists() else ""
        if actual != expected:
            drift.append((path, actual, expected))
    if not drift:
        print("MCP server files are up to date")
        return 0
    for path, actual, expected in drift:
        rel = display(path)
        print(f"DRIFT: {rel}", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)",
                tofile=f"{rel} (expected)",
            )
        )
    print(
        f"\n{len(drift)} MCP server file(s) out of sync — "
        "run mcp/sync.py to regenerate.",
        file=sys.stderr,
    )
    return 1


def main(argv):
    if not SOURCE.exists():
        print(f"source not found: {SOURCE}", file=sys.stderr)
        return 1
    if argv == ["--check"]:
        return check_all()
    if argv:
        print(f"usage: {Path(__file__).name} [--check]", file=sys.stderr)
        return 2
    write_all()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
