#!/usr/bin/env python3
"""Generate every agent's permission config from permissions/permissions.toml.

permissions/permissions.toml is the single source of truth. Run this script
with no arguments to (re)write all generated files; run it with --check to
verify they are up to date (exit 1 with a diff on drift).

Generated files:
  claude/settings.json                  (permissions.allow / deny / ask)
  codex/rules/permissions.rules
  gemini/policies/allowed-tools.toml
  gemini/policies/deny-destructive.toml
  gemini/policies/ask-confirm.toml
  opencode/opencode.json                (permission.bash)
"""

from __future__ import annotations

import difflib
import json
import os
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "permissions" / "permissions.toml"

HEADER_LINES = [
    "GENERATED by permissions/sync.py — do not edit.",
    "Edit permissions/permissions.toml and re-run permissions/sync.py.",
]


# --------------------------------------------------------------------------
# source
# --------------------------------------------------------------------------

def dedupe(items):
    """Order-preserving dedupe. Never use set() — output must be deterministic."""
    return list(dict.fromkeys(items))


def is_glob(entry):
    """A source entry ending in `*` is a glob, not a plain command prefix."""
    return entry.endswith("*")


def parse_source():
    with SOURCE.open("rb") as f:
        data = tomllib.load(f)
    shell = data.get("shell", {})
    claude_extra = data.get("claude", {}).get("extra", {})
    opencode_extra = data.get("opencode", {}).get("extra", {})
    return {
        "allow": dedupe(shell.get("allow", [])),
        "deny": dedupe(shell.get("deny", [])),
        "ask": dedupe(shell.get("ask", [])),
        "claude_extra_allow": dedupe(claude_extra.get("allow", [])),
        "claude_extra_deny": dedupe(claude_extra.get("deny", [])),
        "opencode_extra": opencode_extra,
    }


# --------------------------------------------------------------------------
# claude — claude/settings.json: replace permissions.allow / deny / ask,
# preserve every other key (defaultMode, hooks, statusLine, ...).
# --------------------------------------------------------------------------

def claude_pattern(entry):
    # Colon form matches the command with args or bare; a glob entry is kept
    # literal since Claude's matcher already understands `*`.
    return f"Bash({entry})" if is_glob(entry) else f"Bash({entry}:*)"


def render_claude(rules):
    path = REPO_ROOT / "claude" / "settings.json"
    settings = json.loads(path.read_text())
    perms = settings["permissions"]
    perms["allow"] = [claude_pattern(e) for e in rules["allow"]] + list(
        rules["claude_extra_allow"]
    )
    perms["deny"] = [claude_pattern(e) for e in rules["deny"]] + list(
        rules["claude_extra_deny"]
    )
    perms["ask"] = [claude_pattern(e) for e in rules["ask"]]
    return {path: json.dumps(settings, indent=2, ensure_ascii=False) + "\n"}


# --------------------------------------------------------------------------
# codex — codex/rules/permissions.rules: full regen. Token-prefix matcher,
# so glob entries can't be expressed and fall through to Codex's prompt.
# --------------------------------------------------------------------------

CODEX_DECISION = {"allow": "allow", "deny": "forbidden", "ask": "prompt"}


def codex_rule(entry, decision):
    tokens = ", ".join(json.dumps(t) for t in entry.split())
    return f'prefix_rule(pattern = [{tokens}], decision = "{decision}")'


def render_codex(rules):
    path = REPO_ROOT / "codex" / "rules" / "permissions.rules"
    lines = [f"# {line}" for line in HEADER_LINES]
    lines += [
        "#",
        "# Read-only commands are allowed; remote-publishing and destructive",
        "# ops are forbidden; `ask` commands prompt. Glob entries are skipped",
        "# (see end of file) — Codex's token matcher can't express them.",
    ]
    skipped = []
    for category in ("allow", "deny", "ask"):
        decision = CODEX_DECISION[category]
        emitted = [e for e in rules[category] if not is_glob(e)]
        skipped += [e for e in rules[category] if is_glob(e)]
        if emitted:
            lines.append("")
            for entry in emitted:
                lines.append(codex_rule(entry, decision))
    if skipped:
        lines.append("")
        lines.append(
            "# Skipped — glob entries Codex's token matcher can't express"
        )
        lines.append("# (these fall through to Codex's normal approval prompt):")
        for entry in skipped:
            lines.append(f"#   {entry}")
    return {path: "\n".join(lines) + "\n"}


# --------------------------------------------------------------------------
# gemini — gemini/policies/*.toml: full regen, one file per decision.
# commandPrefix is a string-prefix match, so a glob entry just drops its `*`.
# --------------------------------------------------------------------------

def gemini_prefix(entry):
    return entry[:-1] if is_glob(entry) else entry


def gemini_file(entries, decision, priority, description, deny_message=None):
    lines = [f"# {line}" for line in HEADER_LINES]
    lines.append(f"# {description}")
    prefixes = [gemini_prefix(e) for e in entries]
    if prefixes:
        lines += [
            "",
            "[[rule]]",
            'toolName = "run_shell_command"',
            f'decision = "{decision}"',
            f"priority = {priority}",
        ]
        if deny_message:
            lines.append(f"denyMessage = {json.dumps(deny_message)}")
        lines.append("commandPrefix = [")
        for prefix in prefixes:
            lines.append(f"  {json.dumps(prefix)},")
        lines.append("]")
    return "\n".join(lines) + "\n"


def render_gemini(rules):
    policies = REPO_ROOT / "gemini" / "policies"
    return {
        policies / "allowed-tools.toml": gemini_file(
            rules["allow"], "allow", 100,
            "Allow-list of read-only / safe shell commands.",
        ),
        policies / "deny-destructive.toml": gemini_file(
            rules["deny"], "deny", 200,
            "Block remote-publishing and destructive operations.",
            deny_message=(
                "Remote-publishing or destructive op blocked. "
                "Run manually if intended."
            ),
        ),
        policies / "ask-confirm.toml": gemini_file(
            rules["ask"], "ask_user", 150,
            "Commands that always require user confirmation.",
        ),
    }


# --------------------------------------------------------------------------
# opencode — opencode.json: replace permission.bash, preserve model/provider
# and the permission.<key> toggles from [opencode.extra].
# --------------------------------------------------------------------------

def opencode_patterns(entry):
    # Glob kept literal; a plain prefix gets both the bare and `<prefix> *`
    # forms so `pwd` and `pwd --help` both match.
    return [entry] if is_glob(entry) else [entry, f"{entry} *"]


def render_opencode(rules):
    path = REPO_ROOT / "opencode" / "opencode.json"
    config = json.loads(path.read_text())
    bash = {"*": "ask"}
    for category, decision in (("allow", "allow"), ("deny", "deny"), ("ask", "ask")):
        for entry in rules[category]:
            for pattern in opencode_patterns(entry):
                bash[pattern] = decision
    config["permission"]["bash"] = bash
    for key, value in rules["opencode_extra"].items():
        config["permission"][key] = value
    return {path: json.dumps(config, indent=2, ensure_ascii=False) + "\n"}


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def render_all():
    rules = parse_source()
    files = {}
    files.update(render_claude(rules))
    files.update(render_codex(rules))
    files.update(render_gemini(rules))
    files.update(render_opencode(rules))
    return files


def atomic_write(path, content):
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".sync-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def write_all():
    for path, content in render_all().items():
        atomic_write(path, content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def check_all():
    drift = []
    for path, expected in render_all().items():
        actual = path.read_text() if path.exists() else ""
        if actual != expected:
            drift.append((path, actual, expected))
    if not drift:
        print("permission files are up to date")
        return 0
    for path, actual, expected in drift:
        rel = path.relative_to(REPO_ROOT)
        print(f"DRIFT: {rel}", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)",
                tofile=f"{rel} (expected)",
            )
        )
    print(
        f"\n{len(drift)} permission file(s) out of sync — "
        "run permissions/sync.py to regenerate.",
        file=sys.stderr,
    )
    return 1


def main(argv):
    if not SOURCE.exists():
        print(f"source not found: {SOURCE}", file=sys.stderr)
        return 1
    if argv == ["--check"]:
        return check_all()
    if argv:
        print(f"usage: {Path(__file__).name} [--check]", file=sys.stderr)
        return 2
    write_all()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
