#!/usr/bin/env python3
"""Generate every agent's permission config from permissions/permissions.toml.

permissions/permissions.toml is the single source of truth. Run this script
with no arguments to (re)write all generated files; run it with --check to
verify they are up to date (exit 1 with a diff on drift).

Generated files:
  claude/settings.json                  (permissions.allow / deny / ask)
  claude/settings.autonomous.json       (autonomous-dev profile, Claude only)
  codex/rules/permissions.rules
  antigravity/settings.json             (permissions.allow / deny / ask)
  opencode/opencode.json                (permission.bash)
  pi/permissions.json                   (@gotgenes/pi-permission-system)
  claude/mcp-permissions.json           (PermissionRequest hook policy)
  codex/mcp-permissions.toml            (merged into user config)
"""

from __future__ import annotations

import difflib
import json
import os
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "permissions" / "permissions.toml"

HEADER_LINES = [
    "GENERATED by permissions/sync.py — do not edit.",
    "Edit permissions/permissions.toml and re-run permissions/sync.py.",
]


# --------------------------------------------------------------------------
# source
# --------------------------------------------------------------------------

def dedupe(items):
    """Order-preserving dedupe. Never use set() — output must be deterministic."""
    return list(dict.fromkeys(items))


def is_glob(entry):
    """A source entry ending in `*` is a glob, not a plain command prefix."""
    return entry.endswith("*")


def parse_source():
    with SOURCE.open("rb") as f:
        data = tomllib.load(f)
    shell = data.get("shell", {})
    mcp = data.get("mcp", {})
    claude_extra = data.get("claude", {}).get("extra", {})
    opencode_extra = data.get("opencode", {}).get("extra", {})
    return {
        "allow": dedupe(shell.get("allow", [])),
        "deny": dedupe(shell.get("deny", [])),
        "ask": dedupe(shell.get("ask", [])),
        "mcp_allow": dedupe(mcp.get("allow", [])),
        "mcp_deny": dedupe(mcp.get("deny", [])),
        "mcp_ask": dedupe(mcp.get("ask", [])),
        "claude_extra_allow": dedupe(claude_extra.get("allow", [])),
        "claude_extra_deny": dedupe(claude_extra.get("deny", [])),
        "opencode_extra": opencode_extra,
    }


def mcp_parts(entry):
    server, separator, tool = entry.partition("/")
    if not separator or not server or not tool:
        raise ValueError(f"invalid MCP target: {entry!r}")
    return server, tool


def mcp_native(entry):
    server, tool = mcp_parts(entry)
    return f"mcp__{server}__{tool}"


# --------------------------------------------------------------------------
# claude — claude/settings.json: replace permissions.allow / deny / ask,
# preserve every other key (defaultMode, hooks, statusLine, ...).
# --------------------------------------------------------------------------

def claude_pattern(entry):
    # Colon form matches the command with args or bare; a glob entry is kept
    # literal since Claude's matcher already understands `*`.
    return f"Bash({entry})" if is_glob(entry) else f"Bash({entry}:*)"


def render_claude(rules):
    path = REPO_ROOT / "claude" / "settings.json"
    settings = json.loads(path.read_text())
    perms = settings["permissions"]
    perms["allow"] = (
        [claude_pattern(e) for e in rules["allow"]]
        + [mcp_native(e) for e in rules["mcp_allow"]]
        + list(rules["claude_extra_allow"])
    )
    perms["deny"] = (
        [claude_pattern(e) for e in rules["deny"]]
        + [mcp_native(e) for e in rules["mcp_deny"]]
        + list(rules["claude_extra_deny"])
    )
    perms["ask"] = (
        [claude_pattern(e) for e in rules["ask"]]
        + [mcp_native(e) for e in rules["mcp_ask"]]
    )
    return {path: json.dumps(settings, indent=2, ensure_ascii=False) + "\n"}


def render_claude_mcp_policy(rules):
    path = REPO_ROOT / "claude" / "mcp-permissions.json"
    config = {
        "allow": rules["mcp_allow"],
        "ask": rules["mcp_ask"],
        "deny": rules["mcp_deny"],
    }
    return {path: json.dumps(config, indent=2) + "\n"}


# --------------------------------------------------------------------------
# claude (autonomous) — claude/settings.autonomous.json: same template as the
# normal file, but with allow/deny/ask all emptied so the auto-mode classifier
# judges every tool call. Clearing `deny` is what lets git push etc. through
# (deny overrides every mode); the allow/ask lists would otherwise pre-empt or
# block the classifier. Symlinked by `install.sh --autonomous`.
# --------------------------------------------------------------------------

def render_claude_autonomous(rules):
    path = REPO_ROOT / "claude" / "settings.autonomous.json"
    settings = json.loads((REPO_ROOT / "claude" / "settings.json").read_text())
    perms = settings["permissions"]
    perms["allow"] = []
    perms["deny"] = []
    perms["ask"] = []
    # Autonomous (headless) runs have no human to answer AskUserQuestion; the
    # 60s "proceed with best judgment" fall-through is what keeps them moving.
    # Drop the interactive-only AFK-timeout override so it doesn't deadlock them.
    env = settings.get("env")
    if env:
        env.pop("CLAUDE_AFK_TIMEOUT_MS", None)
        if not env:
            settings.pop("env")
    return {path: json.dumps(settings, indent=2, ensure_ascii=False) + "\n"}


# --------------------------------------------------------------------------
# codex — codex/rules/permissions.rules: full regen. Token-prefix matcher,
# so glob entries can't be expressed and fall through to Codex's prompt.
# --------------------------------------------------------------------------

CODEX_DECISION = {"allow": "allow", "deny": "forbidden", "ask": "prompt"}


def codex_rule(entry, decision):
    tokens = ", ".join(json.dumps(t) for t in entry.split())
    return f'prefix_rule(pattern = [{tokens}], decision = "{decision}")'


def render_codex(rules):
    path = REPO_ROOT / "codex" / "rules" / "permissions.rules"
    lines = [f"# {line}" for line in HEADER_LINES]
    lines += [
        "#",
        "# Read-only commands are allowed; remote-publishing and destructive",
        "# ops are forbidden; `ask` commands prompt. Glob entries are skipped",
        "# (see end of file) — Codex's token matcher can't express them.",
    ]
    skipped = []
    for category in ("allow", "deny", "ask"):
        decision = CODEX_DECISION[category]
        emitted = [e for e in rules[category] if not is_glob(e)]
        skipped += [e for e in rules[category] if is_glob(e)]
        if emitted:
            lines.append("")
            for entry in emitted:
                lines.append(codex_rule(entry, decision))
    if skipped:
        lines.append("")
        lines.append(
            "# Skipped — glob entries Codex's token matcher can't express"
        )
        lines.append("# (these fall through to Codex's normal approval prompt):")
        for entry in skipped:
            lines.append(f"#   {entry}")
    return {path: "\n".join(lines) + "\n"}


# --------------------------------------------------------------------------
# antigravity — antigravity/settings.json: full regen. agy's permissions
# schema wraps each entry in command(...) form (per /cli-features docs).
# The docs only show literal command strings, so glob entries are skipped
# the same way Codex skips them — they fall through to runtime approval.
# --------------------------------------------------------------------------

def antigravity_pattern(entry):
    return f"command({entry})"


def render_antigravity(rules):
    path = REPO_ROOT / "antigravity" / "settings.json"
    settings = json.loads(path.read_text())
    perms = settings.setdefault("permissions", {})
    perms["allow"] = [antigravity_pattern(e) for e in rules["allow"] if not is_glob(e)]
    perms["deny"]  = [antigravity_pattern(e) for e in rules["deny"]  if not is_glob(e)]
    perms["ask"]   = [antigravity_pattern(e) for e in rules["ask"]   if not is_glob(e)]
    for category in ("allow", "deny", "ask"):
        perms[category] += [
            f"mcp({entry})" for entry in rules[f"mcp_{category}"]
        ]
    return {path: json.dumps(settings, indent=2, ensure_ascii=False) + "\n"}


# --------------------------------------------------------------------------
# opencode — opencode.json: replace permission.bash, preserve model/provider
# and the permission.<key> toggles from [opencode.extra].
# --------------------------------------------------------------------------

def opencode_patterns(entry):
    # Glob kept literal; a plain prefix gets both the bare and `<prefix> *`
    # forms so `pwd` and `pwd --help` both match.
    return [entry] if is_glob(entry) else [entry, f"{entry} *"]


def render_opencode(rules):
    path = REPO_ROOT / "opencode" / "opencode.json"
    config = json.loads(path.read_text())
    bash = {"*": "ask"}
    for category, decision in (("allow", "allow"), ("deny", "deny"), ("ask", "ask")):
        for entry in rules[category]:
            for pattern in opencode_patterns(entry):
                bash[pattern] = decision
    permission = {"bash": bash}
    for category, decision in (("allow", "allow"), ("deny", "deny"), ("ask", "ask")):
        for entry in rules[f"mcp_{category}"]:
            server, tool = mcp_parts(entry)
            permission[f"{server}_{tool}"] = decision
    for key, value in rules["opencode_extra"].items():
        permission[key] = value
    config["permission"] = permission
    return {path: json.dumps(config, indent=2, ensure_ascii=False) + "\n"}


def pi_pattern(entry):
    return entry if is_glob(entry) else f"{entry} *"


def render_pi(rules):
    path = REPO_ROOT / "pi" / "permissions.json"
    bash = {"*": "ask"}
    # Pi is last-match-wins, so deny must be emitted last.
    decisions = (("allow", "allow"), ("ask", "ask"), ("deny", "deny"))
    for category, decision in decisions:
        for entry in rules[category]:
            pattern = pi_pattern(entry)
            if pattern in bash:
                del bash[pattern]
            bash[pattern] = decision
    mcp = {"*": "ask"}
    for category, decision in decisions:
        for entry in rules[f"mcp_{category}"]:
            if entry in mcp:
                del mcp[entry]
            mcp[entry] = decision
    config = {
        "$schema": (
            "https://cdn.jsdelivr.net/npm/@gotgenes/"
            "pi-permission-system@23.0.0/schemas/permissions.schema.json"
        ),
        "permission": {
            "*": "allow",
            "bash": bash,
            "mcp": mcp,
        },
    }
    return {path: json.dumps(config, indent=2, ensure_ascii=False) + "\n"}


def render_codex_mcp(rules):
    path = REPO_ROOT / "codex" / "mcp-permissions.toml"
    decisions = {}
    for category, mode in (
        ("allow", "approve"),
        ("ask", "prompt"),
        ("deny", "deny"),
    ):
        for entry in rules[f"mcp_{category}"]:
            decisions[entry] = mode

    servers = {}
    for entry, mode in decisions.items():
        server, tool = mcp_parts(entry)
        servers.setdefault(server, {})[tool] = mode

    lines = [f"# {line}" for line in HEADER_LINES]
    for server in sorted(servers):
        tools = servers[server]
        wildcard = tools.get("*")
        lines.append("")
        lines.append(f"[mcp_servers.{json.dumps(server)}]")
        if wildcard == "deny":
            lines.append("enabled = false")
        elif wildcard:
            lines.append(f"default_tools_approval_mode = {json.dumps(wildcard)}")
        denied = sorted(
            tool for tool, mode in tools.items() if tool != "*" and mode == "deny"
        )
        if denied:
            values = ", ".join(json.dumps(tool) for tool in denied)
            lines.append(f"disabled_tools = [{values}]")
        for tool in sorted(
            tool for tool, mode in tools.items() if tool != "*" and mode != "deny"
        ):
            lines.append("")
            lines.append(
                f"[mcp_servers.{json.dumps(server)}.tools.{json.dumps(tool)}]"
            )
            lines.append(f"approval_mode = {json.dumps(tools[tool])}")
    return {path: "\n".join(lines) + "\n"}


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def render_all():
    rules = parse_source()
    files = {}
    files.update(render_claude(rules))
    files.update(render_claude_mcp_policy(rules))
    files.update(render_claude_autonomous(rules))
    files.update(render_codex(rules))
    files.update(render_antigravity(rules))
    files.update(render_opencode(rules))
    files.update(render_pi(rules))
    files.update(render_codex_mcp(rules))
    return files


def atomic_write(path, content):
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".sync-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def write_all():
    files = render_all()
    originals = {
        path: path.read_text() if path.exists() else None
        for path in files
    }
    try:
        for path, content in files.items():
            atomic_write(path, content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    except BaseException:
        for path, content in originals.items():
            if content is None:
                if path.exists():
                    path.unlink()
            else:
                atomic_write(path, content)
        raise


def check_all():
    drift = []
    for path, expected in render_all().items():
        actual = path.read_text() if path.exists() else ""
        if actual != expected:
            drift.append((path, actual, expected))
    if not drift:
        print("permission files are up to date")
        return 0
    for path, actual, expected in drift:
        rel = path.relative_to(REPO_ROOT)
        print(f"DRIFT: {rel}", file=sys.stderr)
        sys.stderr.writelines(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=f"{rel} (on disk)",
                tofile=f"{rel} (expected)",
            )
        )
    print(
        f"\n{len(drift)} permission file(s) out of sync — "
        "run permissions/sync.py to regenerate.",
        file=sys.stderr,
    )
    return 1


def main(argv):
    if not SOURCE.exists():
        print(f"source not found: {SOURCE}", file=sys.stderr)
        return 1
    if argv == ["--check"]:
        return check_all()
    if argv:
        print(f"usage: {Path(__file__).name} [--check]", file=sys.stderr)
        return 2
    write_all()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
